### PR TITLE
Allow for a larger dependency scope.

### PR DESCRIPTION
**Pull request by Natim**
Refs #735

### CODE REVIEW

**Comment by BenRKarl** [comment]
@Natim thank you for proposing these changes. It shouldn't be an issue to merge this, we'll just need to run the change through our latency test framework to make sure these new dependencies don't cause performance regressions. I'll do this and report back here.

**Review by bobhancockg — APPROVED** [review]

**Comment by BenRKarl** [comment]
@Natim Thanks for following up on this. I had to do a little maintenance on our internal performance framework, but that was fixed as of this morning. I just added this change for testing and should hopefully have enough data on Monday.

**Comment by Natim** [comment]
Hello, we are going back to `google-ads==18.1.0` to not be blocked by this.

**Comment by GiardEmilien** [comment]
We are also stuck by this issue so we cannot use the v12 for now. Do you think this PR will be merged before the sunset date of the v11 (March 31, 2023) ?

**Comment by BenRKarl** [comment]
This change was included in our latest release, [version 20.0.0](https://pypi.org/project/google-ads/20.0.0/), so am closing this out since it's redundant. Thank you for this contribution!

**Pull request closed without merging**
