### PR TITLE
loosen protobuf requirements to meet standard packages reqs

### PR DESCRIPTION
**Pull request by UriSShavit**
Check out the issue that was raised about that matter: https://github.com/googleads/google-ads-python/issues/713

### CODE REVIEW

**Comment by UriSShavit** [comment]
@AndrewMBurke can someone please review?

**Review by bobhancockg — COMMENTED** [review]
Why do we want to do this?

**Comment by AnashOommen** [comment]
@UriSShavit it would be helpful to expand a bit more on *which* standard packages reqs you'd like to meet (names and versions of the packages that interest you). Perhaps this can help us understand the situation better.

**Comment by bobhancockg** [comment]
Airflow has images that support the the supported versions of Google Ads.

**Comment by BenRKarl** [comment]
@UriSShavit just checking whether this PR is still necessary, given the updated Airflow images mentioned in https://github.com/googleads/google-ads-python/issues/713

**Comment by UriSShavit** [comment]
I still think that your requirements should not be that limiting since it breaks all other airflow images in Astronomer and open source version.
I'm going to close this PR as I found a work around (using a lower version of the operator).
I hope that when the time comes and I'll move to a higher Airflow version, I won't encounter this issue again

**Pull request closed without merging**
