### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by davedavis**
Fix typos in comments, parameter names and refactor typos in some variables.

### CODE REVIEW

**Review by BenRKarl — APPROVED** [review]
Thanks @davedavis this is really helpful! Did you scan these files by hand, or did you use an automated tool? We're trying to find a solution to automate fixing grammatical errors in docs/comments so just curious if that's what you used here.

**Review by laurachevalier4 — APPROVED** [review]
Thanks, Dave!

**Comment by BenRKarl** [comment]
@davedavis that's very kind of you to offer, but we're going to try to find an automated solution that saves everyone time and effort.

**Comment by davedavis** [comment]
@BenRKarl 
No worries. Would love to hear about what you come up with that's possible to integrate into a build/testing pipeline. 

For this PR, I only did the examples. In the interim, is it ok for me to do the main package? There's quite a few in there.

**Pull request merged**
