### PR TITLE
Normalize datatypes of customer_ids_to_child_accounts dict to integers

### LINKED ISSUE #364: trouble running get_account_hierarchy.py example?
Hi I'm trying to run the get_account_heirarchy.py example and I keep running into this error:
Traceback (most recent call last):
  File ".\get_account_hierarchy.py", line 202, in <module>
    main(google_ads_client, args.login_customer_id)
  File ".\get_account_hierarchy.py", line 101, in main
    customer_client.id
  File "C:\Python\Python38\lib\site-packages\google\protobuf\message.py", line 94, in __hash__
    raise TypeError('unhashable object')
TypeError: unhashable object

I'm running this command from the project directory:
python .\get_account_hierarchy.py -l 0123456789

Also, I've tried:
python .\get_account_hierarchy.py --manager_customer_id 0123456789

(the argument is actually our manager account customer id and I do have the yaml file with our creds in the directory)

Could you please tell me what I'm doing wrong?

### PR DESCRIPTION
**Pull request by arammaliachi**
- This fixes #364
- Fixes the recursion calls of the printing hierarchy function

### CODE REVIEW

**Comment by arammaliachi** [comment]
Continuation for #379 @BenRKarl. Summary:

- As of v5~ no wrappers are used and APIs response defaults to integers.
- With code as is the `customer_ids_to_child_accounts` dictionary ended up having both strings and ints as keys which was also causing the printing recursive function to only go down 1 level.

**Comment by BenRKarl** [comment]
@arammaliachi looks like this branch has gotten out of sync with the changes we released with version `10.0.0` of the library. Would you mind rebasing this? Assuming the new version of the example has the same issues discussed, this PR looks good. I'll approve after the rebase.

**Comment by arammaliachi** [comment]
Rebased @BenRKarl, I think the formatter got something else though.

**Review by BenRKarl — APPROVED** [review]
The formatting changes look good, we normally just trust it to reduce back-and-forth on styling.

**Review by wihl — APPROVED** [review]
Thanks for your contribution!

**Pull request merged**
